### ISSUE TITLE
ITO Map

### ISSUE THREAD

**Issue by wetneb** [Phyks/stationnements_velos#1]
See also:
http://product.itoworld.com/map/223

**Comment by Phyks** [comment]
Wow, this looks really nice, I did not find it!

This webpage is just a very basic map to show only the bike parkings without capacity to help cyclists nearby tag it (ParisEnSelle is interested in trying to improve the mapping of bike parkings around Paris)

Quick and dirty code, for sure one should rather rely on ITO map for real world use case! :) Thanks for the nice discovery!

**Comment by wetneb** [comment]
Yeah they have lots of similar maps, very useful to fix issues. However your version has the advantage of providing links to the nodes that need fixing (not possible with their raster version).
